app:
  image: ibmcom/swift-ubuntu:3.0.2
  ports:
    - "8080:8080"
  volumes:
    - .:/root/Kitura-Starter
  command: bash -c "cd /root/Kitura-Starter && swift build --clean && swift build && ./.build/debug/Kitura-Starter"
